### ISSUE TITLE
Stucking on "Searching for Serial Port" popup

### ISSUE THREAD

**Issue by ceremcem** [espruino/EspruinoWebIDE#136]
I downloaded WebIDE via `git clone --recursive ...` command and run `npm install`, then run the program via `npm start` command. When I click "connect" button on the left-top, there is a popup opens and it seems stucked. IDE is still responsive, but it seems like it searches for something appropriate, doesn't find it and it will search for that thing forever.

**Comment by gfwilliams** [comment]
As mentioned here: https://github.com/espruino/EspruinoWebIDE#using

It'll be because your version of Node.js and electron don't match, so all the native moduels that NPM installed don't work for electron. If you make sure you have the latest version of each and it should work.

Otherwise you can try a rebuild - see here: http://forum.espruino.com/conversations/283530/

Having said all that, if you use EspruinoTools in command-line mode, that uses Node.js and so should work.

**Comment by gfwilliams** [comment]
Using nw.js now so the situation is a bit better - still requires a rebuild for bluetooth though unless your node + nw.js versions match
