### ISSUE TITLE
Update version of codemirror

### ISSUE THREAD

**Issue by nkolban** [espruino/EspruinoWebIDE#145]
I was using 1v87 and was delighted to find that the JavaScript keywords of `const` and `let` seem to be functional.  However, I notice that they showed as errors in the JavaScript editor in the Web IDE.  I did a very small amount of digging and what I seem to find is that the editor is "codemirror" which, according to the Espruino github is both embedded and hasn't been refreshed in what appears to be 2 years.  If I look at the CodeMirror repository, I see that their last formal release (5.19.0 at the time of writing) was released 3 days ago.  Are there any plans or thoughts on upgrading the embedded codemirror to a later release which would give us support for later JavaScript language constructs?

Looking at their sample here, "const" and "let" are no longer flagged as errors.

**Comment by gfwilliams** [comment]
1v87 still doesn't do `let` or `const` - it's exactly the same as it was before. They're just treated as simple variables, which are named but not referenced so don't produce a referenceerror (probably not the right behaviour, but hey).

So the highlighting is correct (and it's done by jslint, not codemirror). Behaviour is set by flags, even in the current version.

Is there any other perceptible difference between the old and new codemirrors? If not I'd stick with the old one, because I've got more than enough to get on with at the moment and it might risk adding bugs to the IDE.

**Comment by nkolban** [comment]
I entered the following at the latest Codemirror (directly on their web site)
![2016-09-23_9-48-14](https://cloud.githubusercontent.com/assets/3421732/18790058/f49cbb18-8172-11e6-8b14-895acb4318a9.jpg)

and entered the same code in EspruinoWeb IDE and saw:

![2016-09-23_9-49-36](https://cloud.githubusercontent.com/assets/3421732/18790095/13eea404-8173-11e6-9d53-f3bd9f5bc330.jpg)

This is what took me to the WebIDE source code where I saw the CodeMirror was the editor component which took me to CodeMirror which caused me to check what it did with the new JavaScript concepts which caused me to look at the version of CodeMirror in play ... which caused me to create the issue.

https://codemirror.net/

**Comment by gfwilliams** [comment]
Well, as far as I'm concerned that's not a bug.

It's telling you you can't use let and const in Espruino, which you can't.

Well, you can, but it won't be doing what you expect.
