### ISSUE TITLE
Consider blockly GUI improvements

### ISSUE THREAD

**Issue by mickvav** [espruino/EspruinoWebIDE#152]
Hello.
I've just did some coding to make blockly UI able to work with motorshield - 
https://github.com/espruino/EspruinoWebIDE/pull/150
could you please consider adding this code to upstream?

And I have some other questions regarding blockly GUI - it should be possible to write localised blockly (I am interested in russian and ready to contribute, but there may be some other people, interested in other languages), but it seems to me that all main blockly modules reside in minimised form in git - is it possible to unminimise them and are there any chances to get localization code upstream?

**Comment by gfwilliams** [comment]
Yes, I've seen that - it looks great but I'm trying to figure out what to do.

My issue is that Amperka don't actually contribute anything towards Espruino's development or upkeep - they just put it on their board and keep all the profit. However, the additions you've given *don't work with any of the official Espruino boards which do support the project* because they're not Arduino form factor (even if you add the Arduino adaptor shim to the Pico, it won't have the same pins).

It's basically just confusing my paying customers, and encouraging people to buy a board that doesn't actually support Espruino... so it's hard for me to justify.

If your addition supported a wider variety of Arduino-style boards (eg. Pico+Adaptor, Nucleo boards, etc) then it'd be much more helpful - but obviously doing that could make it more complex for kids :(

I'm wondering whether we can add some Settings in the Web IDE that would support enabling/disabling/configuring various blockly components. For example the existing Robot blocks could really do with being turned off by default, as they're just going to confuse most people too. Same for BLE unless you have one of the Bluetooth boards.

Of course the ideal solution would be to allow blocks from an external URL to be used, then teachers could actually make blocks specific to their lessons without having to create a pull request.

Wrt blockly localisation: you'd have to look on Blockly's own website: https://developers.google.com/blockly/

I see no problem with using an unminified version, but I believe Blockly have a specific toolchain for creating the 'merged' blockly files. It looks like they have some kind of system in place already (see top right): https://blockly-demo.appspot.com/static/demos/code/index.html?lang=en

**Comment by gfwilliams** [comment]
edit: language changing code here: https://blockly-demo.appspot.com/static/demos/code/code.js

**Comment by mickvav** [comment]
Well, I've found that it's relatively easy to append translations - just copy en.js to ru.js and translate strings inside. But it turns that blockly.html has to contain references to all the languages of interest.
Thus, may it would be a good idea to create some generation script, that can  be used to selectively include there different feature sets (e.g. MotorShield or Robot or BLE or whatever) and chose languages of interest?

**Comment by gfwilliams** [comment]
Ok, great! I'm not against adding all the needed languages to blockly.html if you want to - there's probably not a great amount of text in each one.

A generation script could be good, but I imagine a lot of people would have difficulty moving from a chrome web app to installing it in Chrome themselves. If the JS file for blocks could also contain XML for the 'toolbox' then perhaps it would be possible to load dynamically (in fact presumably translations could be loaded dynamically as well?).

**Comment by mickvav** [comment]
Well, as for now, I've moved almost all Espruino- and Amperka- user-visible strings to en.js and created ru.js. Also added config option to make it possible to use blockly.local.html. This allows user to create custom local config without touching existing sources.

**Comment by mickvav** [comment]
Well, looks like it's this issue should be closed - pull request merged, some more code added, well done.

**Comment by gfwilliams** [comment]
Cool - thanks!
