### ISSUE TITLE
short if without assignment cause syntax error

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#153]
ha - syntax checker is back and found something I do not unterstand

line of code:

```
funcs.length > 0 ? funcs.shift().apply(scope, arguments) : end.call(scope);
````

syntax error:

![bildschirmfoto 2016-11-24 um 15 04 40](https://cloud.githubusercontent.com/assets/15932646/20602524/efa5e712-b25d-11e6-9a97-57282f403ed4.JPG)

ok this can be easy written as:

```
if (funcs.length > 0 ) {
  funcs.shift().apply(scope, arguments);
}
else {
  end.call(scope);
}
```

[complete code](https://github.com/espruino/Espruino/blob/master/libs/network/esp8266/tests/modules/Async.js)

**Comment by gfwilliams** [comment]
Yes - it's because you're using something that is generally designed to return a result in a way where the result isn't used.

Sure, it's not *wrong* to do what you're doing, but most of the time it could be a sign that you've made a mistake.

It's a bit like warning about `a==5;` and `if (a=5) ...`

I'm not sure that's really a problem. If you know what you're doing you can ignore it...

**Comment by MaBecker** [comment]
I just thought  this is something you should know

just to be sure that this is not a bug with the syntax checker ;-)

**Comment by gfwilliams** [comment]
It's using http://jshint.com/ - there are a whole bunch of settings: http://jshint.com/docs/options/

I've already added a few: https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/core/editorJavaScript.js#L29

So if you find some that you think I should add, let me know - it's not a big deal to put them in :)
