### ISSUE TITLE
How to turn off style checking?

### ISSUE THREAD

**Issue by trusktr** [espruino/EspruinoWebIDE#177]
I like my own code style. Can I turn off all the red X marks in the editor?

**Comment by trusktr** [comment]
Thanks for this, btw, it's so awesome!!

**Comment by gfwilliams** [comment]
Do you have an example of code that it complains about? Generally the red `X`s are reserved for actual coding errors.

**Comment by trusktr** [comment]
For example leaving off semi colons. I don't use them.

**Comment by gfwilliams** [comment]
You'll might get yourself in a lot of trouble not using semi-colons, since Espruino doesn't implement JS's slightly odd use of newlines as delimiters.

But if you want to turn it off you can download your own copy of the IDE and disable with the linting here: https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/core/editorJavaScript.js#L28

**Comment by trusktr** [comment]
Cool. I haven't ran into trouble yet. Maybe I'm lucky!
