### ISSUE TITLE
Update Blockly files

### ISSUE THREAD

**Issue by rachel-fenichel** [espruino/EspruinoWebIDE#191]
Hi there!  I heard about your project from the Bay Area Maker Faire.  I'm on the Blockly team, so it's always fun to see projects that are using Blockly to help people get into coding.

You may want to update your Blockly files (blockly_compressed.js, blocks_compressed.js, and javascript_compressed.js).  

We've significantly improved Blockly in the past four years.  Here are some things you can get with an update:
- Better performance for block and workspace dragging
- Touch and multitouch support
- Bugfixes all around, including lots of browser compatibility issues
- Typed variables
- Undo and redo
- Hooks for custom alert, confirm, and prompt modals 

If you haven't significantly customized Blockly this should be a straightforward upgrade.  

Cheers,
Rachel

**Comment by gfwilliams** [comment]
Hi Rachel, that's great, thanks! Who was it that had Espruino at the Maker Faire?

I'd love to update - touch support especially would be really handy for mobile/tablet use with Web Bluetooth.

Apart from Espruino-specific blocks, the only thing I thing I needed on Blockly was a block to handle multiline text since it's often handy for someone to put a bit of JavaScript 'glue' offscreen if they want to do something a bit custom. Unfortunately the block I was using for that doesn't appear to work on new versions of Blockly.

There was a pull request for multiline fields at https://github.com/google/blockly/pull/30 but as far as I can tell it was closed and the changes you requested to get it into core never actually happened. 

Sadly I haven't had the time to try and get anything sorted myself. I'll see about pulling the updated block out of the PR and getting that to work with the new Blockly though.

**Comment by gfwilliams** [comment]
Well that was a bit of a nightmare. However it is done now.

I have (I believe) modified TextArea to work off the top of TextInput - but I'm afraid I don't have time to package it for a PR, or the knowledge of Blockly to know whether it is done in the correct way or not. You're welcome to use it if you want to though.

**Comment by rachel-fenichel** [comment]
I don't know who had Espruino--I heard about it from someone who was there and knows I do Blockly.

I'm glad you were able to upgrade so quickly.  

As I mentioned in google/blockly#30, we don't currently have headcount to implement this field.  But I'll keep your implementation in mind when it comes up again.

Cheers,
Rachel
