### ISSUE TITLE
Windows "native" release

### ISSUE THREAD

**Issue by AkosLukacs** [espruino/EspruinoWebIDE#206]
Hi Gordon!

Afaik, only the native version supports projects, and using local modules, and that's a handy feature. But the latest native release was 0.70.6. Tried to build the node version using WSL, but `sudo npm install nw -g` failed with `EACCES: permission denied, mkdir '/usr/lib/node_modules/nw/nwjs'` search lead to nowhere.
Sooo, any plans to release a new win native version? Or are there build instructions for the win native version somewhere?
Or should I just switch to commandline tools & VSCode? :)

**Comment by AkosLukacs** [comment]
Nevermind, just cloned the latest, npm install + npm start in regular commandline, and it's working!

**Comment by gfwilliams** [comment]
Ok, I'll make a note to do a release anyway.

The Chrome Web App version supports projects as well, and that should work fine :)

**Comment by AkosLukacs** [comment]
Thanks for pointing to the Chrome Web App. For some reason, project settings did not show up in the Chrome App. Maybe reinstalling it helped?

**Comment by gfwilliams** [comment]
This may help as there are a bunch of different versions - actually it's my fault for using the wrong naming, it gets quite confusing! http://www.espruino.com/Web+IDE

There's the Chrome App on the Chrome Web Store: https://chrome.google.com/webstore/detail/espruino-web-ide/bleoifhkdalbjfbobjackfdifdneehpo

That should work and have projects in it.

The actual Web App on https://www.espruino.com/ide/ won't have projects support though, because there is no API that allows directory access from a website that I'm aware of :(

**Comment by AkosLukacs** [comment]
We are talking about the same thing :)
Installed the App from the Chrome Web Store a long time ago. Had a separate "app" icon. But there was no project option. Reinstalled this morning, and there is a project option now. Or maybe because it is Chrome Canary, and something works differently? No idea honestly...

**Comment by gfwilliams** [comment]
I think somewhere around 4 months ago I made a mistake and Projects disappeared, but it was only for a week or so - must have just been bad luck!
