### ISSUE TITLE
How to change the tabulator size?

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoWebIDE#245]
Can't find the option in the WEB IDE to change the tabulator size. 

What am I missing?

**Comment by gfwilliams** [comment]
That's because I don't think there is one.

It could be added to https://github.com/espruino/EspruinoWebIDE/blob/master/js/core/editorJavaScript.js#L67
 but I wonder quite where you stop - there are so many settings that could be pulled in for the editor.

I guess we could add a JSON-formatted string of options for CodeMirror so it could be customised as required

**Comment by MaBecker** [comment]
> I guess we could add a JSON-formatted string of options for CodeMirror so it could be customised as required

That would be great

**Comment by James-Livesey** [comment]
I've created PR #248 to address the issue of not being able to change the indentation size, as well as having the option to choose between spaces and tabs. The idea of having a JSON options field would be awesome though! I may start working on that if I have time.

**Comment by MaBecker** [comment]
Indentation is enough.
