### ISSUE TITLE
Bugs: Tabs overlap buttons in top right corner

### ISSUE THREAD

**Issue by thyttan** [espruino/EspruinoWebIDE#301]
# The bugs
![Screenshot from 2024-09-29 17-47-36](https://github.com/user-attachments/assets/9f705b2d-0262-4504-9808-0c40d418b708)
*In this picture we see that the file tabs draw over the buttons in the corner. The user is still able to interact with the buttons.*

![Screenshot from 2024-09-29 17-48-11](https://github.com/user-attachments/assets/12c31632-9186-4293-95f2-397bad483415)
*In this picture we see the tabs wrap to fit on screen. Now the buttons are no longer interactable with the mouse.*

The pictures above show two bugs - overlap of tabs and buttons; buttons becoming unavailable to the user when the tab bar wraps (resolved by closing tabs untill it doesn't wrap anymore).

The bugs are not new. I think I've seen them since the tabs were introduced. Since they aren't too problematic I didn't report them before.

# Some potential solutions or mitigating changes:
- Before starting to wrap the tab bar, push it to the left.
- Shrink tab sizes when the tab bar becomes overpopulated (like chromium/firefox browsers).
  - *Additionally introduce horizontal scrolling when individual tabs become to narrow (like firefox browser).*

# My system
OS: Fedora Linux 40 (Workstation Edition)
Browser: Chromium Version 129.0.6668.58 (Official Build) Fedora Project (64-bit)

**Comment by gfwilliams** [comment]
Thanks - yes, it's been an issue with tab overlap since tabs were introduced.

Scrolling seems like it could be a neat solution, and hopefully can just be CSS - although as you say pushing it to the left first would be neat.

One thing that might be handy is right now the tabs are hard-coded to start at 50%, but really the start point should be set to the position of the splitter in the middle.

If anyone wants to contribute a PR that'd be great!

**Comment by thyttan** [comment]
Tried out the changes - neat, thanks!
