### ISSUE TITLE
Add shortcut key support

### ISSUE THREAD

**Issue by mattbrailsford** [espruino/EspruinoWebIDE#42]
Allow defining custom key commands along with icons (ie "Cmd + S" for save).

**Comment by CWBudde** [comment]
I know that this is an old issue, but since I am working quite often with the editor lately, I wonder what is needed to customize the shortcuts? Or at least at some other common shortcuts like "CTRL + R" for replace or "F3" for continue search. Both are somewhat standard on windows systems and I'm sure many other users will wonder about this as well.

Also, I think it would be nice to switch the default settings to something known from other editors. With this, the user can make the IDE feel as much home as the default editor does.

**Comment by gfwilliams** [comment]
The editor itself is based on CodeMirror, so if you google it there should a bunch of info on how to change key bindings. The actual instantiation is here: https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/core/editorJavaScript.js#L40 so it shouldn't be too hard to add/change things.

Having an option in the settings page for it would be really neat

**Comment by CWBudde** [comment]
I have already started looking into it, hence the pull request for winnus. So far the EspruinoWebIDE doesn't compile out of the box on my machine, mostly because of errors in the underlying libraries. I'll see if I can get them fixed (or at least reported).

Once I have a working setup, I'll see if I can work on the code mirror editor.

Btw. I noticed that the version which is used here is quite old. Is there any reason for it or would it make sense to update it along the process?

**Comment by gfwilliams** [comment]
Great! Thanks for the PR - I've got a bit of catching up to do after Easter but I'll try and take a look and merge this as soon as I can.

> I noticed that the version which is used here is quite old. Is there any reason for it or would it make sense to update it along the process?

Yes, you could definitely update it. There's no reason it's older other than I didn't come across anything that was broken and didn't have time to update and then test that everything still worked :)

**Comment by sebi5361** [comment]
Would it be possible to add a shortcut to switch between the _editor panel_ and the _REPL panel_?

**Comment by gfwilliams** [comment]
That sounds like a great idea! Any thoughts on possible shortcut keys?

**Comment by sebi5361** [comment]
**ctrl+`** would be a good choice I think:
- it is already the shortcut in _Microsoft Visual Studio Code_ for this action,
- it seems to be compatible with _Google Chrome_.

**Comment by gfwilliams** [comment]
Sounds good to me...

**Comment by gfwilliams** [comment]
Closing this, it's implemented now - as well as a way to add shortcuts easily via https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/js/plugins/keyShortcuts.js
